name: CI

on:
  push:
    branches:
      - master
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1

      - run: bundle install --jobs 4 --retry 3

      - run: bundle exec rake test VERBOSE=1
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
